### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by IssacSchneizer** [t-e-l/tel#14]
**Feature description**
the current package name for the app is same as that of main termux app. this forces users to use tel for everything termux related instead of just as a launcher. also forces to uninstall the main termux app and setup everything in tez. its painful to migrate entire termux setup to tez. so i request a change of the package name if possible.
 

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.
NA

**Comment by v1nc** [comment]
> All termux packages build with prefix path /data/data/com.termux/files/usr So , if maintainer change package name to com.tez He must change all termux package perfix to /data/data/com.tez/files/usr So that's big changes.

This is right. Changing the package name requires many changes that go deep into the terminal emulation. Since TEL is our free time project, it wont be possible to do this in the near future. We would accept PRs about it but I dont expect anyone to do this voluntarily.

There are some options to work around the resulted inconvenience:
- you can backup all user data from `/data/data/com.termux/` to your sd card and restore them after installing TEL
- you can also backup a list of installed packages to restore them later
- if you depend on many manually installed packages, it could theoretically be possible to backup the whole `/data/data/com.termux/` directory and restore it after TEL installation. You will get some problems with the TEL setup which you need to fix with `tel-setup` or manually, but your packages should work. It is possible that you will face additional problems if you are using a Termux version released after 02/11/21, because thats the latest upstream commits that were merged into TEL atm. I dont know from anybody who did this before, but it could work, so if you try it please report the results.
